name: 'GitHub Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: '导出代码'
        uses: actions/checkout@v1
      - name: '获取天气脚本'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: '发送邮件'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report (${{env.REPORT_DATE}})
          body: file://result.html
          to: 673658660@qq.com
          from: GitHub Actions
          content_type: text/html
